import React, { useState } from "react";
import { FileText, Folder, Scale, Sparkles } from "lucide-react";

export default function ToolsPanel({ caseData, battleData }) {
  const [activeTab, setActiveTab] = useState("notes");

  // Only show notes/evidence/precedents from battle data (generated by Daytona)
  // Don't fall back to case data - user must click "Generate AI Insights (Daytona)" first
  const displayNotes = (battleData?.battle_notes && battleData.battle_notes.trim() !== '') 
    ? battleData.battle_notes 
    : '';
  
  const displayEvidence = (battleData?.battle_evidence && battleData.battle_evidence.length > 0)
    ? battleData.battle_evidence 
    : [];
  
  const displayPrecedents = (battleData?.battle_precedents && battleData.battle_precedents.length > 0)
    ? battleData.battle_precedents 
    : [];
  
  const hasAIInsights = battleData?.insights_last_updated;

  if (!caseData) {
    return <div className="bg-[#1a1f3a]/50 rounded-lg border border-[#d4af37]/20 p-4 text-gray-400">Loading case data...</div>;
  }

  return (
    <div className="bg-[#1a1f3a]/50 rounded-lg border border-[#d4af37]/20 overflow-hidden">
      {/* Tab Headers */}
      <div className="w-full grid grid-cols-3 bg-[#151a2e] border-b border-[#d4af37]/20">
        <button
          onClick={() => setActiveTab("notes")}
          className={`inline-flex items-center justify-center px-3 py-3 text-sm font-medium transition-all ${
            activeTab === "notes" ? "bg-[#d4af37]/20 text-[#d4af37]" : "text-gray-400 hover:text-gray-300"
          }`}
        >
          <FileText className="w-4 h-4 mr-2" />
          <span className="hidden sm:inline">Notes</span>
        </button>
        <button
          onClick={() => setActiveTab("evidence")}
          className={`inline-flex items-center justify-center px-3 py-3 text-sm font-medium transition-all ${
            activeTab === "evidence" ? "bg-[#d4af37]/20 text-[#d4af37]" : "text-gray-400 hover:text-gray-300"
          }`}
        >
          <Folder className="w-4 h-4 mr-2" />
          <span className="hidden sm:inline">Evidence</span>
        </button>
        <button
          onClick={() => setActiveTab("precedents")}
          className={`inline-flex items-center justify-center px-3 py-3 text-sm font-medium transition-all ${
            activeTab === "precedents" ? "bg-[#d4af37]/20 text-[#d4af37]" : "text-gray-400 hover:text-gray-300"
          }`}
        >
          <Scale className="w-4 h-4 mr-2" />
          <span className="hidden sm:inline">Precedent</span>
        </button>
      </div>

      {/* Tab Content */}
      <div className="p-4 space-y-3 h-64 overflow-y-auto">
        {activeTab === "notes" && (
          <>
            {hasAIInsights && (
              <div className="flex items-center gap-2 px-2 py-1.5 bg-purple-500/10 border border-purple-400/30 rounded-md mb-3">
                <Sparkles className="w-3 h-3 text-purple-400" />
                <p className="text-[10px] text-purple-300 uppercase tracking-wide">AI-Generated Insights</p>
              </div>
            )}
            <div>
              <h4 className="text-sm font-semibold text-[#d4af37] mb-2">Strategic Notes</h4>
              {displayNotes ? (
                <p className="text-xs text-gray-300 leading-relaxed mb-3 whitespace-pre-wrap">
                  {displayNotes}
                </p>
              ) : (
                <p className="text-xs text-gray-500 italic">
                  Click "Generate AI Insights (Daytona)" to analyze this case and generate strategic notes.
                </p>
              )}
            </div>
          </>
        )}

        {activeTab === "evidence" && (
          <>
            {hasAIInsights && displayEvidence.length > 0 && (
              <div className="flex items-center gap-2 px-2 py-1.5 bg-purple-500/10 border border-purple-400/30 rounded-md mb-3">
                <Sparkles className="w-3 h-3 text-purple-400" />
                <p className="text-[10px] text-purple-300 uppercase tracking-wide">AI-Generated Insights</p>
              </div>
            )}
            {displayEvidence.length > 0 ? (
              <>
                <div className="mb-2">
                  <p className="text-xs text-gray-500 uppercase tracking-wide">Available Evidence ({displayEvidence.length})</p>
                </div>
                {displayEvidence.map((item, index) => (
                  <div
                    key={index}
                    className="p-3 bg-[#151a2e] rounded-lg border border-[#4a90e2]/30 hover:border-[#4a90e2]/50 transition-colors"
                  >
                    <div className="flex items-start justify-between mb-1">
                      <p className="text-xs font-semibold text-[#60a5fa]">{item.name}</p>
                      <span className="text-[10px] px-2 py-0.5 bg-[#4a90e2]/20 text-[#60a5fa] rounded-full uppercase">
                        {item.type}
                      </span>
                    </div>
                    <p className="text-xs text-gray-400 leading-relaxed">{item.content}</p>
                    {item.relevance && (
                      <p className="text-[10px] text-purple-400 mt-1 italic">Relevance: {item.relevance}</p>
                    )}
                  </div>
                ))}
              </>
            ) : (
              <div className="text-center py-8">
                <Folder className="w-12 h-12 text-gray-600 mx-auto mb-2" />
                <p className="text-xs text-gray-400">No evidence available.</p>
              </div>
            )}
          </>
        )}

        {activeTab === "precedents" && (
          <>
            {hasAIInsights && displayPrecedents.length > 0 && (
              <div className="flex items-center gap-2 px-2 py-1.5 bg-purple-500/10 border border-purple-400/30 rounded-md mb-3">
                <Sparkles className="w-3 h-3 text-purple-400" />
                <p className="text-[10px] text-purple-300 uppercase tracking-wide">AI-Generated Insights</p>
              </div>
            )}
            {displayPrecedents.length > 0 ? (
              <>
                <div className="mb-2">
                  <p className="text-xs text-gray-500 uppercase tracking-wide">Relevant Case Law ({displayPrecedents.length})</p>
                </div>
                {displayPrecedents.map((precedent, index) => (
                  <div
                    key={index}
                    className="p-3 bg-[#151a2e] rounded-lg border border-[#10b981]/30 hover:border-[#10b981]/50 transition-colors"
                  >
                    <div className="flex items-start gap-2">
                      <Scale className="w-3 h-3 text-[#10b981] mt-0.5 flex-shrink-0" />
                      <p className="text-xs text-gray-300 leading-relaxed">{precedent}</p>
                    </div>
                  </div>
                ))}
              </>
            ) : (
              <div className="text-center py-8">
                <Scale className="w-12 h-12 text-gray-600 mx-auto mb-2" />
                <p className="text-xs text-gray-400">No precedents listed.</p>
              </div>
            )}
          </>
        )}
      </div>
    </div>
  );
}